name: Python CI with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build Docker Image
        run: |
          docker build -t hello-docker .
      -
        name: Login to Docker Hub
        run: |
          docker login -u uthpakhi -p dckr_pat_nhEBnTXwdO2RWY7LEsM_Adxugxo
          docker tag hello-docker uthpakhi/hello-docker
          docker push uthpakhi/hello-docker
      -  
        name: Run Docker Container
        run: |
          docker run -d --name my-container -p 8080:80 uthpakhi/hello-docker