name: Python CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build Docker Image
        run: |
          docker build -t docker-created .
      -
        name: Login to Docker Hub
        run: |
          docker login -u azharali0564 -p dckr_pat_8g1vdm3YxB6KZH_U-WZUBDt1OUM
          docker tag docker-created azharali0564/docker-created
          docker push azharali0564/docker-created
      -  
        name: Run Docker Container
        run: |
          docker run -d --name my-container -p 8080:80 azharali0564/docker-created